# Generated by Django 4.2.29 on 2026-03-27 15:17

import apps.detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectionobject',
            new_name='detection_o_class_n_6d6664_idx',
            old_name='detection_o_class_n_dcd9a1_idx',
        ),
        migrations.RenameIndex(
            model_name='detectiontask',
            new_name='detection_t_task_no_d93657_idx',
            old_name='detection_t_task_no_f8a0dc_idx',
        ),
        migrations.RenameIndex(
            model_name='detectiontask',
            new_name='detection_t_status_0325f6_idx',
            old_name='detection_t_status_18144a_idx',
        ),
        migrations.RenameIndex(
            model_name='detectiontask',
            new_name='detection_t_created_882958_idx',
            old_name='detection_t_created_e9bfae_idx',
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='task_no',
            field=models.CharField(default=apps.detection.models.generate_task_no, max_length=32, unique=True),
        ),
    ]
