# Generated by Django 4.2.29 on 2026-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_rename_detection_o_class_n_dcd9a1_idx_detection_o_class_n_6d6664_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectiontask",
            name="preprocess_algorithm_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="detectiontask",
            name="preprocess_algorithms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="detectiontask",
            name="preprocess_enable_gamma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="detectiontask",
            name="preprocess_mode",
            field=models.CharField(default="off", max_length=16),
        ),
        migrations.AddField(
            model_name="detectiontask",
            name="preprocess_profile",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
