# Generated by Django 4.2.29 on 2026-03-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdataset',
            old_name='class_names',
            new_name='_class_names',
        ),
        migrations.RenameIndex(
            model_name='trainingjob',
            new_name='training_jo_status_20fc5c_idx',
            old_name='training_jo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingjob',
            new_name='training_jo_job_no_11616e_idx',
            old_name='training_jo_job_no_idx',
        ),
    ]
