# Generated by Django 4.2.29 on 2026-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_class_names_trainingdataset__class_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='baseline_map50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='baseline_map50_95',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='baseline_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='baseline_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='baseline_status',
            field=models.CharField(choices=[('NONE', 'None'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NONE', max_length=16),
        ),
    ]
