# Generated by Django 4.2.29 on 2026-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_add_baseline_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="prepared_dataset_path",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_algorithm_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_algorithms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_enable_gamma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_manifest_path",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_mode",
            field=models.CharField(default="off", max_length=16),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="preprocess_profile",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
